export enum TaiwanRegionType {
  TPE = 'tpe',
  TPH = 'tph',
  TYC = 'tyc',
  TXG = 'txg',
  TNN = 'tnn',
  KHH = 'khh',
  HSH = 'hsh',
  MAL = 'mal',
  CWH = 'cwh',
  NTC = 'ntc',
  YLH = 'ylh',
  CHY = 'chy',
  IUH = 'iuh',
  ILN = 'iln',
  HWA = 'hwa',
  TTT = 'ttt',
  PEH = 'peh',
  KMN = 'kmn',
  LNN = 'lnn',
  KEE = 'kee',
  HSC = 'hsc',
  CYI = 'cyi'
}